dist: xenial
branches:
  only:
    - master
language: csharp
solution: eform-trashinspectionBase/Microting.eFormTrashInspectionBase.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build Microting.eFormTrashInspectionBase.sln
  - dotnet test -v n Microting.eFormTrashInspectionBase.Integration.Tests/Microting.eFormTrashInspectionBase.Integration.Tests.csproj
